version: 2
project_name: burrow

before:
  hooks:
    - go mod tidy
    - sh -c 'cd web && npm ci && npm run build'

builds:
  - id: server
    main: ./cmd/server
    binary: burrowd
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w
      - -X github.com/ankoehn/burrow/internal/version.Version={{.Version}}
      - -X github.com/ankoehn/burrow/internal/version.Commit={{.Commit}}
      - -X github.com/ankoehn/burrow/internal/version.Date={{.Date}}

  - id: client
    main: ./cmd/client
    binary: burrow
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, arm, "386"]
    goarm: ["7"]
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w
      - -X github.com/ankoehn/burrow/internal/version.Version={{.Version}}
      - -X github.com/ankoehn/burrow/internal/version.Commit={{.Commit}}
      - -X github.com/ankoehn/burrow/internal/version.Date={{.Date}}

archives:
  - id: server
    ids: [server]
    formats: [tar.gz]
    name_template: >-
      burrowd_{{ .Os }}_
      {{- if eq .Arch "arm" }}armv7
      {{- else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
    format_overrides:
      - goos: windows
        formats: [zip]
  - id: client
    ids: [client]
    formats: [tar.gz]
    name_template: >-
      burrow_{{ .Os }}_
      {{- if eq .Arch "arm" }}armv7
      {{- else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

dockers_v2:
  - id: burrow
    images:
      - ghcr.io/ankoehn/burrow
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64

signs:
  - cmd: cosign
    artifacts: checksum
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature=${signature}"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^test:'
      - '^docs:'
