version: 2
project_name: burrow

before:
  hooks:
    - go mod tidy
    - sh -c 'cd web && npm ci && npm run build'

builds:
  - id: server
    main: ./cmd/server
    binary: burrowd
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w
      - -X github.com/ankoehn/burrow/internal/version.Version={{.Version}}
      - -X github.com/ankoehn/burrow/internal/version.Commit={{.Commit}}
      - -X github.com/ankoehn/burrow/internal/version.Date={{.Date}}

  - id: client
    main: ./cmd/client
    binary: burrow
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, arm, "386"]
    goarm: ["7"]
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w
      - -X github.com/ankoehn/burrow/internal/version.Version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - "ghcr.io/ankoehn/burrow:{{ .Version }}-amd64"
      - "ghcr.io/ankoehn/burrow:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64
  - image_templates:
      - "ghcr.io/ankoehn/burrow:{{ .Version }}-arm64"
      - "ghcr.io/ankoehn/burrow:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/ankoehn/burrow:{{ .Version }}"
    image_templates:
      - "ghcr.io/ankoehn/burrow:{{ .Version }}-amd64"
      - "ghcr.io/ankoehn/burrow:{{ .Version }}-arm64"
  - name_template: "ghcr.io/ankoehn/burrow:latest"
    image_templates:
      - "ghcr.io/ankoehn/burrow:latest-amd64"
      - "ghcr.io/ankoehn/burrow:latest-arm64"

signs:
  - cmd: cosign
    artifacts: checksum
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature=${signature}"
      - "${artifact}"
