// test-only — never deploy this shape.
// Paths to the committed client cert + key at test/harness/certs/.
// Generated by ../harness/certs/gen.sh — see Phase 2.1 of the plan.

import * as path from "node:path";

// process.cwd() === test/e2e when Playwright runs (same pattern as stack.ts).
// Certs live in the shared harness dir (test/harness/certs), one level up + over.
export const CLIENT_CERT_PATH = path.resolve(process.cwd(), "..", "harness", "certs", "client.crt");
export const CLIENT_KEY_PATH = path.resolve(process.cwd(), "..", "harness", "certs", "client.key");
export const CA_CERT_PATH = path.resolve(process.cwd(), "..", "harness", "certs", "ca.crt");
