// test-only — never deploy this shape.
// Paths to the committed client cert + key at test/e2e/certs/.
// Generated by certs/gen.sh — see Phase 2.1 of the plan.

import * as path from "node:path";

// process.cwd() === test/e2e when Playwright runs (same pattern as stack.ts).
export const CLIENT_CERT_PATH = path.resolve(process.cwd(), "certs", "client.crt");
export const CLIENT_KEY_PATH = path.resolve(process.cwd(), "certs", "client.key");
export const CA_CERT_PATH = path.resolve(process.cwd(), "certs", "ca.crt");
