// test-only — never deploy this shape.
// Paths to the committed client cert + key at test/integration/full/certs/.
// Generated by certs/gen.sh — see Phase 2.1 of the plan.

import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const CLIENT_CERT_PATH = path.resolve(__dirname, "..", "certs", "client.crt");
export const CLIENT_KEY_PATH = path.resolve(__dirname, "..", "certs", "client.key");
export const CA_CERT_PATH = path.resolve(__dirname, "..", "certs", "ca.crt");
